version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9001:8000"
    volumes:
      - .:/app
      - /home/application_files/website_backend/settings.ini:/app/config/settings.ini

